# Generated by Django 3.1.6 on 2021-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrelog',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
