# Generated by Django 3.1.6 on 2021-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
