# Generated by Django 3.1.6 on 2021-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrelog',
            name='user_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrelog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
