# Generated by Django 3.1.6 on 2021-02-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210221_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrelog',
            name='topic',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SquirreLogs', to='api.squirreltopic'),
        ),
    ]
