# Generated by Django 3.1.6 on 2021-02-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210220_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.squirrelog'),
        ),
    ]
