# Generated by Django 3.1.6 on 2021-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210408_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrelog',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='squirrelog',
            name='replies',
            field=models.ManyToManyField(default=None, related_name='log_replies', through='api.ManageReplies', to='api.SquirreLog'),
        ),
    ]
