# Generated by Django 3.1.6 on 2021-03-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfps'),
        ),
    ]
