# Generated by Django 3.1.6 on 2021-03-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_2149'),
        ('api', '0002_user_pfp'),
    ]

    operations = [
    ]
