# Generated by Django 3.1.6 on 2021-02-20 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210217_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrelog',
            name='user_story',
        ),
        migrations.AddField(
            model_name='squirrelog',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
