# Generated by Django 3.1.6 on 2021-03-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20210325_2029'),
        ('api', '0003_merge_20210325_1609'),
        ('api', '0003_merge_20210325_1612'),
    ]

    operations = [
    ]
