# Generated by Django 3.1.6 on 2021-04-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210408_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrelog',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
