# Generated by Django 3.1.6 on 2021-03-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20210325_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='squirrelog',
            name='replies',
            field=models.ManyToManyField(related_name='log_replies', to='api.SquirreLog'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfps'),
        ),
    ]
