# Generated by Django 3.1.6 on 2021-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210221_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_posts',
            field=models.ManyToManyField(related_name='disliked_posts', to='api.SquirreLog'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_posts', to='api.SquirreLog'),
        ),
    ]
