# Generated by Django 3.1.6 on 2021-03-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210325_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='api.squirrelog')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='api.squirrelog')),
            ],
        ),
        migrations.AlterField(
            model_name='squirrelog',
            name='replies',
            field=models.ManyToManyField(related_name='log_replies', through='api.ManageReplies', to='api.SquirreLog'),
        ),
    ]
