# Generated by Django 3.1.4 on 2021-02-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrelog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='squirrelog',
            name='topic',
        ),
        migrations.CreateModel(
            name='TopicalSquirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.squirrelog')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.squirreltopic')),
            ],
        ),
        migrations.AddField(
            model_name='squirrelog',
            name='topics',
            field=models.ManyToManyField(related_name='SquirreLogs', through='api.TopicalSquirrels', to='api.SquirrelTopic'),
        ),
    ]
