# Generated by Django 3.1.6 on 2021-02-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210219_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrelog',
            name='owner',
        ),
    ]
