# Generated by Django 3.1.4 on 2021-02-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210221_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicalSquirrels',
            new_name='TopicalSquirrel',
        ),
    ]
