# Generated by Django 3.1.4 on 2021-02-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210221_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrelog',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
