# Generated by Django 3.1.4 on 2021-02-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_squirrelog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicalsquirrel',
            name='owner',
        ),
        migrations.AddField(
            model_name='squirrelog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
