# Generated by Django 3.1.6 on 2021-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210221_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirreltopic',
            name='logs',
            field=models.ManyToManyField(related_name='SquirrelTopics', through='api.TopicalSquirrel', to='api.SquirreLog'),
        ),
    ]
