# Generated by Django 3.1.4 on 2021-02-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210219_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='squirrelog',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.squirreltopic'),
        ),
    ]
